# Generated by Django 4.1.1 on 2022-10-05 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamesave",
            name="open_options",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
